on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: npm

      - name: Install dependencies
        run: npm install octokit

      - name: Echo TOKEN
        run: echo $TOKEN  # This line echoes the value of the TOKEN environment variable
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
